# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import vetapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0002_auto_20160414_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('text_color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='white', max_length=5)),
                ('image', models.ImageField(upload_to=vetapp.models.vet_uploads)),
            ],
        ),
    ]
