# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0003_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
