# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0004_auto_20160415_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
